

[target.aarch64-linux-android]
ar = "C:/Users/camer/AndroidStudioProjects/AndroidRustFFI/rust-lib/NDK/aarch64-linux-android-ar"
linker = "C:/Users/camer/AndroidStudioProjects/AndroidRustFFI/rust-lib/NDK/arm64/bin/aarch64-linux-android-clang.cmd"
[target.armv7-linux-androideabi]
ar = "C:/Users/camer/AndroidStudioProjects/AndroidRustFFI/rust-lib/NDK/arm/bin/arm-linux-androideabi-ar"
linker = "C:/Users/camer/AndroidStudioProjects/AndroidRustFFI/rust-lib/NDK/arm/bin/arm-linux-androideabi-clang.cmd"
[target.i686-linux-android]
ar = "C:/Users/camer/AndroidStudioProjects/AndroidRustFFI/rust-lib/NDK/x86/bin/i686-linux-android-ar"
linker = "C:/Users/camer/AndroidStudioProjects/AndroidRustFFI/rust-lib/NDK/x86/bin/i686-linux-android-clang.cmd"